import Head from 'next/head'
import styles from '@/styles/Home.module.css'
import { prisma } from '../lib/prisma';
import { GetStaticProps } from 'next';
import { User } from '@prisma/client';



export default function Home(props: { users: User[] }) {

  return (
    <>
      <Head>
        <title>next.js_prisma</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <h1>next.js_prisma</h1>
        <ul>
          {
            props.users.map((user: User) => {
              return <li key={user.id}>
                {user.name}
              </li>
            })
          }
        </ul>
      </main>
    </>
  )
}

export const getStaticProps: GetStaticProps = async () => {
  const users: User[] = await prisma.user.findMany({});

  return { props: { users } };
};
